# Generated by Django 5.1 on 2026-05-26 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SavedScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('annual_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rate_type', models.CharField(choices=[('variable', 'Variable'), ('fixed', 'Fixed')], max_length=10)),
                ('repayment_type', models.CharField(choices=[('principal_and_interest', 'Principal & Interest'), ('interest_only', 'Interest Only')], max_length=25)),
                ('repayment_frequency', models.CharField(choices=[('weekly', 'Weekly'), ('fortnightly', 'Fortnightly'), ('monthly', 'Monthly')], max_length=15)),
                ('loan_term_years', models.PositiveSmallIntegerField()),
                ('repayment_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_interest', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_repayment', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
