# Generated by Django 5.1 on 2026-05-26 09:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mortgage', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedscenario',
            name='offset_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Offset account for variable rate loans only', max_digits=12),
        ),
        migrations.AlterField(
            model_name='savedscenario',
            name='annual_rate',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='savedscenario',
            name='loan_term_years',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(40)]),
        ),
    ]
